name       : breeze-snow-cursor-theme
version    : 5.16.0
release    : 8
source     :
    - https://cdn.download.kde.org/stable/plasma/5.16.0/breeze-5.16.0.tar.xz : eb37e75b6a463648edd1b421e06531054a361af9b60e0e4fb1588a36212a4dae
license    : GPL-2.0
component  : desktop.theme
summary    : Breeze Snow cursor theme
description: |
    Breeze Snow cursor theme
install    : |
    cursorDir=$installdir/usr/share/icons/breeze-snow-cursor
    install -dm00755 $cursorDir/
    cp -R $workdir/cursors/Breeze_Snow/Breeze_Snow/* $cursorDir/
