name       : breeze-snow-cursor-theme
version    : 5.15.2
release    : 4
source     :
    - https://cdn.download.kde.org/stable/plasma/5.15.2/breeze-5.15.2.tar.xz : 682bc6c7669f5440b64157e57b2b1a157234dca1c7e721874a52bb1117bb4e54
license    : GPL-2.0
component  : desktop.theme
summary    : Breeze Snow cursor theme
description: |
    Breeze Snow cursor theme
install    : |
    cursorDir=$installdir/usr/share/icons/breeze-snow-cursor
    install -dm00755 $cursorDir/
    cp -R $workdir/cursors/Breeze_Snow/Breeze_Snow/* $cursorDir/
