name       : breeze-snow-cursor-theme
version    : 5.15.3
release    : 5
source     :
    - https://cdn.download.kde.org/stable/plasma/5.15.3/breeze-5.15.3.tar.xz : 4be0b50deb6a3b42e3c09461ebef76f0af758c400c998b627bc72931d8b3fe50
license    : GPL-2.0
component  : desktop.theme
summary    : Breeze Snow cursor theme
description: |
    Breeze Snow cursor theme
install    : |
    cursorDir=$installdir/usr/share/icons/breeze-snow-cursor
    install -dm00755 $cursorDir/
    cp -R $workdir/cursors/Breeze_Snow/Breeze_Snow/* $cursorDir/
