name       : breeze-snow-cursor-theme
version    : 5.11.0
release    : 3
source     :
    - https://download.kde.org/stable/plasma/5.11.0/breeze-5.11.0.tar.xz : d46449e0845f46e5e4ba6a7e0976701e08c16c271e3bfd189a2c56d7e9370180
license    : GPL-2.0
component  : desktop.theme
summary    : Breeze Snow cursor theme
description: |
    Breeze Snow cursor theme
install    : |
    cursorDir=$installdir/usr/share/icons/breeze-snow-cursor
    install -dm00755 $cursorDir/
    cp -R $workdir/cursors/Breeze_Snow/Breeze_Snow/* $cursorDir/
