name       : breeze-snow-cursor-theme
version    : 5.15.5
release    : 7
source     :
    - https://download.kde.org/stable/plasma/5.15.5/breeze-5.15.5.tar.xz : a13de0472dacd5240c3d38d0841ea7b9098405cf1f8cff77504d1824d09dcac4
license    : GPL-2.0
component  : desktop.theme
summary    : Breeze Snow cursor theme
description: |
    Breeze Snow cursor theme
install    : |
    cursorDir=$installdir/usr/share/icons/breeze-snow-cursor
    install -dm00755 $cursorDir/
    cp -R $workdir/cursors/Breeze_Snow/Breeze_Snow/* $cursorDir/
