name       : breeze-snow-cursor-theme
version    : 5.16.1
release    : 9
source     :
    - https://download.kde.org/stable/plasma/5.16.1/breeze-5.16.1.tar.xz : bf4fba98f83311365f249d706689f327380db2de61ca7bb2a8442472e0b1316e
license    : GPL-2.0
component  : desktop.theme
summary    : Breeze Snow cursor theme
description: |
    Breeze Snow cursor theme
install    : |
    cursorDir=$installdir/usr/share/icons/breeze-snow-cursor
    install -dm00755 $cursorDir/
    cp -R $workdir/cursors/Breeze_Snow/Breeze_Snow/* $cursorDir/
