name       : breeze-snow-cursor-theme
version    : 5.16.2
release    : 10
source     :
    - https://cdn.download.kde.org/stable/plasma/5.16.2/breeze-5.16.2.tar.xz : bd33e97fd21a2314d5d6a8e90327851c8aa75bf2583feb56dcb0a2485c950a9d
license    : GPL-2.0
component  : desktop.theme
summary    : Breeze Snow cursor theme
description: |
    Breeze Snow cursor theme
install    : |
    cursorDir=$installdir/usr/share/icons/breeze-snow-cursor
    install -dm00755 $cursorDir/
    cp -R $workdir/cursors/Breeze_Snow/Breeze_Snow/* $cursorDir/
